version: "3"

volumes:
  postgres-data:
    driver: local
  ephesus-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./postgres.env
    ports:
      - 5432:5432
    labels:
      - docker-volume-backup.stop-during-backup=true

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis-data:/data
      - ./redis-users.acl:/etc/redis/users.acl
    ports:
      - 6379:6379
    command: redis-server --aclfile /etc/redis/users.acl

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    restart: always
    env_file:
      - ./keycloak.env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start"]

  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    restart: always
    env_file:
      - ./oauth2proxy.env
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    ports:
      - 4180:4180
    depends_on:
      - keycloak

  ephesus:
    build: /usr/local/src/greek-room/ephesus
    restart: always
    volumes:
      - ephesus-data:/data
      - /shared-data/ephesus-data/analysis-requests:/analysis-requests
    env_file:
      - ./ephesus.env
    ports:
      - 8000:8000
    depends_on:
      - oauth2proxy
      - redis
    develop:
      watch:
        - action: sync+restart
          path: /usr/local/src/greek-room/ephesus/ephesus
          target: /ephesus
        - action: rebuild
          path: /usr/local/src/greek-room/ephesus/requirements.txt

  ephesus-db-migrations:
    build: /usr/local/src/greek-room/ephesus
    volumes:
      - ephesus-data:/data
    env_file:
      - ./ephesus.env
    depends_on:
      - ephesus
    command: alembic -c ephesus/database/alembic.ini upgrade head

  backup:
    image: offen/docker-volume-backup:v2.34.0
    restart: always
    env_file: ./backup.env
    volumes:
      - ephesus-data:/backup/ephesus_database
      - postgres-data:/backup/postgres_database
      - redis-data:/backup/redis_database
      - /usr/local/backups/docker-volumes:/archive
